// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.sereneproject.collector.domain;

import java.lang.String;

privileged aspect ServerGroup_Roo_JavaBean {
    
    public String ServerGroup.getName() {
        return this.name;
    }
    
    public void ServerGroup.setName(String name) {
        this.name = name;
    }
    
}
